[package]
name = "advent_of_code"
description = "Advent of Code solutions in Rust"
version = "0.1.0"
edition = "2021"
authors = ["Antonio Mamić <antoniomamic007@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["cargo"] }
md5 = "0.7.0"
